version: 2.1

executors:
  maven-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies 
          command: mvn clean install -DskipTests
      - persist_to_workspace:
          root: ~/repo
          paths:
            - target
  test:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            mvn test   
             test_count=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.build.directory}/surefire-reports/*.xml' exec:exec | grep -c '<testcase')
            if [ "$test_count" -lt 3 ]; then
              echo "Not enough tests passed. Only $test_count tests passed.";
              exit 1;
            fi        

  build-docker-image:
    executor: maven-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build Docker Image
          command: |
            docker build -t bindugopinathan/project_split_and_share:tagname .
            
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push bindugopinathan/project_split_and_share:tagname
  deploy:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: echo "Deploying application to the production environment..."

workflows:
  ci_flow:
    jobs:
      - build
      - test:
          requires:
            - build

  cicd_flow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-docker-image:
          requires:
            - test
      - deploy:
          requires:
            - build-docker-image
            
        

